
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-15
owner: ucsb-cs156-f25
repo_name: team02-f25-15
pull_requests: [{"author":{"id":"U_kgDOB3B5Cw","is_bot":false,"login":"novuxx888","name":""},"headRefName":"andrew-form_component","number":69,"title":"Andrew form component","url":"https://github.com/ucsb-cs156-f25/team02-f25-15/pull/69"},{"author":{"id":"U_kgDOCL5eCw","is_bot":false,"login":"timmywin","name":"tim"},"headRefName":"tvn-RecommendationRequest-backend","number":67,"title":"Copy files for Backend CRUD API RecommendationRequest from team01 #26","url":"https://github.com/ucsb-cs156-f25/team02-f25-15/pull/67"},{"author":{"id":"U_kgDOB1PefA","is_bot":false,"login":"guntashgill","name":""},"headRefName":"gg_ucsborganization_fixtures","number":66,"title":"Gg ucsborganization fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-15/pull/66"},{"author":{"id":"U_kgDOBpYh_w","is_bot":false,"login":"Shibainuinuinu","name":"Kelvin Fang"},"headRefName":"Kelvin-helprequests-fixtures","number":65,"title":"Kelvin helprequests fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-15/pull/65"},{"author":{"id":"U_kgDOBpYh_w","is_bot":false,"login":"Shibainuinuinu","name":"Kelvin Fang"},"headRefName":"Kelvin-HelpRequest-backend","number":64,"title":"Kelvin - copy backend CRUD operations from team01 helprequest table","url":"https://github.com/ucsb-cs156-f25/team02-f25-15/pull/64"},{"author":{"id":"U_kgDOB3B5Cw","is_bot":false,"login":"novuxx888","name":""},"headRefName":"andrew","number":61,"title":"copied over crud operations","url":"https://github.com/ucsb-cs156-f25/team02-f25-15/pull/61"}]
